version: 2
jobs:
  build:
    docker:
      - image: microsoft/azure-cli

    steps:
      - checkout
      - run: az --version
      # replace with Azure's username and password
      #- run: az login -u <USERNAME> -p <PASSWORD>
      #- run: ~/repo/test.sh

